# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-omq" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kubectl-omq"],
          must_succeed: false
    end
  end

  version "omqctl-v0.8.0"

  on_macos do
    on_arm do
      sha256 "136c5db014dd599653ebc8529cc07dd96221b7e03ef209744d02cff4b9d7e430"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "634423fadd12181d671136a479addc9aca90cd2eb1c6e32493e6825e93543c5b"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b2565c807ead3c0a30f04880d45c9adf71854ffb7a7e1d8b0788c669ab34759"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "099d3bfc8ad2f19719decd76975e6fb05da0c961100d7ee097e3457c9ce72d1c"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Linux_x86_64.tar.gz"
    end
  end

  name "kubectl-omq"
  desc "kubectl plugin that manages OctopusMQ clusters in Kubernetes."
  homepage "https://www.cybroslabs.com/en/products/octopusmq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-omq"
  binary "kubectl_complete-omq"
  manpage "man/kubectl-omq-list.1.gz"
  manpage "man/kubectl-omq-queue-create.1.gz"
  manpage "man/kubectl-omq-queue-delete-item.1.gz"
  manpage "man/kubectl-omq-queue-delete.1.gz"
  manpage "man/kubectl-omq-queue-enqueue.1.gz"
  manpage "man/kubectl-omq-queue-ensure.1.gz"
  manpage "man/kubectl-omq-queue-info.1.gz"
  manpage "man/kubectl-omq-queue-list.1.gz"
  manpage "man/kubectl-omq-queue-noop.1.gz"
  manpage "man/kubectl-omq-queue-pause.1.gz"
  manpage "man/kubectl-omq-queue-pull.1.gz"
  manpage "man/kubectl-omq-queue-resize.1.gz"
  manpage "man/kubectl-omq-queue-resume.1.gz"
  manpage "man/kubectl-omq-queue.1.gz"
  manpage "man/kubectl-omq-replica-destroy.1.gz"
  manpage "man/kubectl-omq-replica-list.1.gz"
  manpage "man/kubectl-omq-replica.1.gz"
  manpage "man/kubectl-omq-storage-create.1.gz"
  manpage "man/kubectl-omq-storage-delete-key.1.gz"
  manpage "man/kubectl-omq-storage-delete.1.gz"
  manpage "man/kubectl-omq-storage-ensure.1.gz"
  manpage "man/kubectl-omq-storage-get-keys.1.gz"
  manpage "man/kubectl-omq-storage-get.1.gz"
  manpage "man/kubectl-omq-storage-info.1.gz"
  manpage "man/kubectl-omq-storage-list.1.gz"
  manpage "man/kubectl-omq-storage-lock-any.1.gz"
  manpage "man/kubectl-omq-storage-noop.1.gz"
  manpage "man/kubectl-omq-storage-set.1.gz"
  manpage "man/kubectl-omq-storage.1.gz"
  manpage "man/kubectl-omq-test-benchmark.1.gz"
  manpage "man/kubectl-omq-test-verify.1.gz"
  manpage "man/kubectl-omq-test.1.gz"
  manpage "man/kubectl-omq-version.1.gz"
  manpage "man/kubectl-omq.1.gz"

  # No zap stanza required

  caveats <<~EOS
    kubectl-omq is a kubectl plugin: run it as 'kubectl omq'. It reaches OctopusMQ clusters through the current kube context; the kube user needs get and list on statefulsets and pods, and create on pods/portforward.
  EOS
end
