# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-omq" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kubectl-omq"],
          must_succeed: false
    end
  end

  version "omqctl-v0.8.1"

  on_macos do
    on_arm do
      sha256 "3b012eb1b12d2a6b320f1362a852e0e6f81083f50555d12093b1f8723c61e19a"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a18fc58e7ed87b4e7f24c5f70540b95b11040494d552c2e1015596d10956dfa7"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a4000e830cad2ef2def5c0adb2360b24a186e269434491ec01f97ea6ecb0fde4"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ccfde1931920cee5673a563ce0cce438bff6d7faee9a6d5866e46bf08e59dd0"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/kubectl-omq_Linux_x86_64.tar.gz"
    end
  end

  name "kubectl-omq"
  desc "kubectl plugin that manages OctopusMQ clusters in Kubernetes."
  homepage "https://www.cybroslabs.com/en/products/octopusmq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-omq"
  binary "kubectl_complete-omq"
  manpage "man/kubectl-omq-list.1.gz"
  manpage "man/kubectl-omq-queue-create.1.gz"
  manpage "man/kubectl-omq-queue-delete-item.1.gz"
  manpage "man/kubectl-omq-queue-delete.1.gz"
  manpage "man/kubectl-omq-queue-enqueue.1.gz"
  manpage "man/kubectl-omq-queue-ensure.1.gz"
  manpage "man/kubectl-omq-queue-info.1.gz"
  manpage "man/kubectl-omq-queue-list.1.gz"
  manpage "man/kubectl-omq-queue-noop.1.gz"
  manpage "man/kubectl-omq-queue-pause.1.gz"
  manpage "man/kubectl-omq-queue-pull.1.gz"
  manpage "man/kubectl-omq-queue-resize.1.gz"
  manpage "man/kubectl-omq-queue-resume.1.gz"
  manpage "man/kubectl-omq-queue.1.gz"
  manpage "man/kubectl-omq-replica-destroy.1.gz"
  manpage "man/kubectl-omq-replica-list.1.gz"
  manpage "man/kubectl-omq-replica.1.gz"
  manpage "man/kubectl-omq-storage-create.1.gz"
  manpage "man/kubectl-omq-storage-delete-key.1.gz"
  manpage "man/kubectl-omq-storage-delete.1.gz"
  manpage "man/kubectl-omq-storage-ensure.1.gz"
  manpage "man/kubectl-omq-storage-get-keys.1.gz"
  manpage "man/kubectl-omq-storage-get.1.gz"
  manpage "man/kubectl-omq-storage-info.1.gz"
  manpage "man/kubectl-omq-storage-list.1.gz"
  manpage "man/kubectl-omq-storage-lock-any.1.gz"
  manpage "man/kubectl-omq-storage-noop.1.gz"
  manpage "man/kubectl-omq-storage-set.1.gz"
  manpage "man/kubectl-omq-storage.1.gz"
  manpage "man/kubectl-omq-test-benchmark.1.gz"
  manpage "man/kubectl-omq-test-verify.1.gz"
  manpage "man/kubectl-omq-test.1.gz"
  manpage "man/kubectl-omq-version.1.gz"
  manpage "man/kubectl-omq.1.gz"

  # No zap stanza required

  caveats <<~EOS
    kubectl-omq is a kubectl plugin: run it as 'kubectl omq'. It reaches OctopusMQ clusters through the current kube context; the kube user needs get and list on statefulsets and pods, and create on pods/portforward.
  EOS
end
