# This file was generated by GoReleaser. DO NOT EDIT.
cask "omqctl" do
  version "omqctl-v0.4.2"

  on_macos do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "98af9075755d9145ad0304985239000fe970fb54d49e24bb45083d8c9850a012"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "1c887241d9a38712b6cc6dd9276ff0de76ba345f3275a30ca46bfb369e779793"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "40642368aefa6630d85797e2202f03c9bfde79b3ad671e3cc8f44e84c65700bf"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "8d5d7c67d05ec32d2f9979ca3d26680af89b66d1cc8fa743aa434ac59dbeb240"
    end
  end

  name "omqctl"
  desc "omqctl controls the OctopusMQ deployments."
  homepage "https://www.cybroslabs.com/en/products/octopusmq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omqctl"
  manpage "man/omqctl-benchmark.1.gz"
  manpage "man/omqctl-config-get-context.1.gz"
  manpage "man/omqctl-config-list-contexts.1.gz"
  manpage "man/omqctl-config-set-context.1.gz"
  manpage "man/omqctl-config-view.1.gz"
  manpage "man/omqctl-config.1.gz"
  manpage "man/omqctl-queue-commit.1.gz"
  manpage "man/omqctl-queue-create.1.gz"
  manpage "man/omqctl-queue-delete-item.1.gz"
  manpage "man/omqctl-queue-delete.1.gz"
  manpage "man/omqctl-queue-enqueue.1.gz"
  manpage "man/omqctl-queue-ensure.1.gz"
  manpage "man/omqctl-queue-info.1.gz"
  manpage "man/omqctl-queue-list.1.gz"
  manpage "man/omqctl-queue-noop.1.gz"
  manpage "man/omqctl-queue-pause.1.gz"
  manpage "man/omqctl-queue-pull.1.gz"
  manpage "man/omqctl-queue-requeue.1.gz"
  manpage "man/omqctl-queue-resize.1.gz"
  manpage "man/omqctl-queue-resume.1.gz"
  manpage "man/omqctl-queue.1.gz"
  manpage "man/omqctl-storage-create.1.gz"
  manpage "man/omqctl-storage-delete-key.1.gz"
  manpage "man/omqctl-storage-delete.1.gz"
  manpage "man/omqctl-storage-ensure.1.gz"
  manpage "man/omqctl-storage-get-keys.1.gz"
  manpage "man/omqctl-storage-get.1.gz"
  manpage "man/omqctl-storage-info.1.gz"
  manpage "man/omqctl-storage-list.1.gz"
  manpage "man/omqctl-storage-lock-any.1.gz"
  manpage "man/omqctl-storage-noop.1.gz"
  manpage "man/omqctl-storage-release.1.gz"
  manpage "man/omqctl-storage-set.1.gz"
  manpage "man/omqctl-storage.1.gz"
  manpage "man/omqctl-version.1.gz"
  manpage "man/omqctl.1.gz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omqctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The omqctl tool is used to control the OctopusMQ deployments.
  EOS
end
