# This file was generated by GoReleaser. DO NOT EDIT.
cask "omqctl" do
  version "omqctl-v0.5.11"

  on_macos do
    on_intel do
      sha256 "0d3d41510b1c8b23531df8ec0a7edc642f48457dbe1e982f5d3886e06d0b144b"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "a87430570275912b08307815989da881618abd9a7e7e585768fe7d67aa3c4323"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  on_linux do
    on_intel do
      sha256 "8be636a40f72a703f581dd91aa47aefb8807bd5743e30d46c9c6fbc5256c65e5"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "516b8629430e7bdae506fffd598c420fe334a2abbe14c700a16e21b577364758"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  name "omqctl"
  desc "omqctl controls the OctopusMQ deployments."
  homepage "https://www.cybroslabs.com/en/products/octopusmq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omqctl"
  manpage "man/omqctl-config-get-context.1.gz"
  manpage "man/omqctl-config-list-contexts.1.gz"
  manpage "man/omqctl-config-set-context.1.gz"
  manpage "man/omqctl-config-view.1.gz"
  manpage "man/omqctl-config.1.gz"
  manpage "man/omqctl-queue-commit.1.gz"
  manpage "man/omqctl-queue-create.1.gz"
  manpage "man/omqctl-queue-delete-item.1.gz"
  manpage "man/omqctl-queue-delete.1.gz"
  manpage "man/omqctl-queue-enqueue.1.gz"
  manpage "man/omqctl-queue-ensure.1.gz"
  manpage "man/omqctl-queue-info.1.gz"
  manpage "man/omqctl-queue-list.1.gz"
  manpage "man/omqctl-queue-noop.1.gz"
  manpage "man/omqctl-queue-pause.1.gz"
  manpage "man/omqctl-queue-pull.1.gz"
  manpage "man/omqctl-queue-requeue.1.gz"
  manpage "man/omqctl-queue-resize.1.gz"
  manpage "man/omqctl-queue-resume.1.gz"
  manpage "man/omqctl-queue.1.gz"
  manpage "man/omqctl-storage-create.1.gz"
  manpage "man/omqctl-storage-delete-key.1.gz"
  manpage "man/omqctl-storage-delete.1.gz"
  manpage "man/omqctl-storage-ensure.1.gz"
  manpage "man/omqctl-storage-get-keys.1.gz"
  manpage "man/omqctl-storage-get.1.gz"
  manpage "man/omqctl-storage-info.1.gz"
  manpage "man/omqctl-storage-list.1.gz"
  manpage "man/omqctl-storage-lock-any.1.gz"
  manpage "man/omqctl-storage-noop.1.gz"
  manpage "man/omqctl-storage-release.1.gz"
  manpage "man/omqctl-storage-set.1.gz"
  manpage "man/omqctl-storage.1.gz"
  manpage "man/omqctl-test-benchmark.1.gz"
  manpage "man/omqctl-test-verify.1.gz"
  manpage "man/omqctl-test.1.gz"
  manpage "man/omqctl-version.1.gz"
  manpage "man/omqctl.1.gz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omqctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The omqctl tool is used to control the OctopusMQ deployments.
  EOS
end
