# This file was generated by GoReleaser. DO NOT EDIT.
cask "omqctl" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/omqctl"],
          must_succeed: false
    end
  end

  version "omqctl-v0.8.3"

  on_macos do
    on_arm do
      sha256 "0787ea8e7939ec4c6c793916f16fcf132dafcc43900e7856c349c8a6ce685c0e"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "da4463f18c0741f78967a4359e86a1ed845460cce43153c1b98fbcc0582fddfe"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d14119a74292ad85874f7067e55fb2024d5b12db08a3b41ef7f7a6eeba20a67"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "27dc6f2c578ce5341d111796b2c7b60b0f9d674c3c7e0572f84cb7fcbe5273c8"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/omqctl_Linux_x86_64.tar.gz"
    end
  end

  name "omqctl"
  desc "omqctl controls the OctopusMQ deployments."
  homepage "https://www.cybroslabs.com/en/products/octopusmq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omqctl"
  manpage "man/omqctl-config-get-context.1.gz"
  manpage "man/omqctl-config-list-contexts.1.gz"
  manpage "man/omqctl-config-set-context.1.gz"
  manpage "man/omqctl-config-view.1.gz"
  manpage "man/omqctl-config.1.gz"
  manpage "man/omqctl-queue-create.1.gz"
  manpage "man/omqctl-queue-delete-item.1.gz"
  manpage "man/omqctl-queue-delete.1.gz"
  manpage "man/omqctl-queue-enqueue.1.gz"
  manpage "man/omqctl-queue-ensure.1.gz"
  manpage "man/omqctl-queue-info.1.gz"
  manpage "man/omqctl-queue-list.1.gz"
  manpage "man/omqctl-queue-noop.1.gz"
  manpage "man/omqctl-queue-pause.1.gz"
  manpage "man/omqctl-queue-pull.1.gz"
  manpage "man/omqctl-queue-resize.1.gz"
  manpage "man/omqctl-queue-resume.1.gz"
  manpage "man/omqctl-queue.1.gz"
  manpage "man/omqctl-replica-destroy.1.gz"
  manpage "man/omqctl-replica-list.1.gz"
  manpage "man/omqctl-replica.1.gz"
  manpage "man/omqctl-storage-create.1.gz"
  manpage "man/omqctl-storage-delete-key.1.gz"
  manpage "man/omqctl-storage-delete.1.gz"
  manpage "man/omqctl-storage-ensure.1.gz"
  manpage "man/omqctl-storage-get-keys.1.gz"
  manpage "man/omqctl-storage-get.1.gz"
  manpage "man/omqctl-storage-info.1.gz"
  manpage "man/omqctl-storage-list.1.gz"
  manpage "man/omqctl-storage-lock-any.1.gz"
  manpage "man/omqctl-storage-noop.1.gz"
  manpage "man/omqctl-storage-set.1.gz"
  manpage "man/omqctl-storage.1.gz"
  manpage "man/omqctl-test-benchmark.1.gz"
  manpage "man/omqctl-test-verify.1.gz"
  manpage "man/omqctl-test.1.gz"
  manpage "man/omqctl-version.1.gz"
  manpage "man/omqctl.1.gz"

  # No zap stanza required

  caveats <<~EOS
    The omqctl tool is used to control the OctopusMQ deployments.
  EOS
end
