# This file was generated by GoReleaser. DO NOT EDIT.
cask "openxml-embedded-extractor" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/openxml-embedded-extractor"],
          must_succeed: false
    end
  end

  version "openxml-embedded-extractor-v0.0.14"

  on_macos do
    on_arm do
      sha256 "b07abf5c9c4d079f3b07561c2cecef1a797ade1c49a6f308303a433b265f4f0e"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee11a4f3451557d71e15c0e60a76401e0237dacccfdaf5f0044ea8d27b622c5c"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "04e1a852aa6ca4465773bc6652dc854b767993351d03472fe7886566b00cb778"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d087ef5c85a345a09fa80f55f5e4625c649105ca18bbf134531d2d32de69f68e"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_x86_64.tar.gz"
    end
  end

  name "openxml-embedded-extractor"
  desc "Extract embedded files from OpenXML documents (docx, xlsx, pptx)."
  homepage "https://www.cybroslabs.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openxml-embedded-extractor"
  manpage "man/openxml-embedded-extractor-version.1.gz"
  manpage "man/openxml-embedded-extractor.1.gz"

  # No zap stanza required

  caveats <<~EOS
    The openxml-embedded-extractor tool extracts embedded files from OpenXML documents (docx, xlsx, pptx).
  EOS
end
