# This file was generated by GoReleaser. DO NOT EDIT.
cask "openxml-embedded-extractor" do
  version "openxml-embedded-extractor-v0.0.9"

  on_macos do
    on_intel do
      sha256 "d782513c4cd832c9f3b7e1075ccc5beb76a2287fbac6426bca7c8e1206e5b6ec"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "995bfb75e49c3782d0531fbd5452836f6c1a65b2b9f23aa0f0104172296626b4"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  on_linux do
    on_intel do
      sha256 "c481793ff49e1ef0a3a54901c07875850e08d3a9c60ef21f808190c8d1424463"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "9aa39ffa111b76316c1fe57ef820d7b6d6fb21484e4ae992edbf0abb2b2afc7e"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  name "openxml-embedded-extractor"
  desc "Extract embedded files from OpenXML documents (docx, xlsx, pptx)."
  homepage "https://www.cybroslabs.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openxml-embedded-extractor"
  manpage "man/openxml-embedded-extractor-version.1.gz"
  manpage "man/openxml-embedded-extractor.1.gz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openxml-embedded-extractor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The openxml-embedded-extractor tool extracts embedded files from OpenXML documents (docx, xlsx, pptx).
  EOS
end
