# This file was generated by GoReleaser. DO NOT EDIT.
cask "openxml-embedded-extractor" do
  name "openxml-embedded-extractor"
  desc "Extract embedded files from OpenXML documents (docx, xlsx, pptx)."
  homepage "https://www.cybroslabs.com/"
  version "openxml-embedded-extractor-v0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openxml-embedded-extractor"
  manpage "man/openxml-embedded-extractor-version.1.gz"
  manpage "man/openxml-embedded-extractor.1.gz"

  on_macos do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "8e0a4cd0f73099e5e3b61263ce7014a3c3fc80894b750d57ab5b98049d3923ad"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "0390716b9a94658c7ddb468419715fa3ddf215a23a167c7868f400a96d13352e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "a90377ae85466ed8eac5e6d189564c4961d10aec92bcce9d8d3fea8dc2a24055"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/openxml-embedded-extractor_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "5d844c20b413a5a0c7619b11c24ca577d3e07512e9a5c93c8ef17066d7382ef0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openxml-embedded-extractor"]
    end
  end

  caveats do
    "The openxml-embedded-extractor tool extracts embedded files from OpenXML documents (docx, xlsx, pptx)."
  end

  # No zap stanza required
end
