# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroctl" do
  version "ouroctl-v1.1.0"

  on_macos do
    on_intel do
      sha256 "7ed38721b02515640e031d1a81c5a00fdcf016740219aaff290cef4677e55e05"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "fa65f0f2fed828342078dde46a38f8dc2196e3da2c27f901ab3c56731156f54f"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  on_linux do
    on_intel do
      sha256 "37714fe1e901375d0bf887cf4bdea0ab1e77566db3e610a904ea59273fc9fcbc"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
    on_arm do
      sha256 "8d4d7d2fb3fabedfc90146d6a206baaef73ad44fd79f9c009cdfdfa4c58b7a4a"
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
    end
  end

  name "ouroctl"
  desc "ouroctl controls the OuroPlatform deployments."
  homepage "https://www.cybroslabs.com/en/products/openhes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroctl"
  manpage "man/ouroctl-apply-business-object-component-types.1.gz"
  manpage "man/ouroctl-apply-business-object-components.1.gz"
  manpage "man/ouroctl-apply-business-object-types.1.gz"
  manpage "man/ouroctl-apply-business-objects.1.gz"
  manpage "man/ouroctl-apply-data-zones.1.gz"
  manpage "man/ouroctl-apply-field-descriptors.1.gz"
  manpage "man/ouroctl-apply-gulf.1.gz"
  manpage "man/ouroctl-apply-license.1.gz"
  manpage "man/ouroctl-apply-roles.1.gz"
  manpage "man/ouroctl-apply-screen-configs.1.gz"
  manpage "man/ouroctl-apply-secrets.1.gz"
  manpage "man/ouroctl-apply-template.1.gz"
  manpage "man/ouroctl-apply-translation.1.gz"
  manpage "man/ouroctl-apply.1.gz"
  manpage "man/ouroctl-delete-template.1.gz"
  manpage "man/ouroctl-delete.1.gz"
  manpage "man/ouroctl-get-business-object-component-types.1.gz"
  manpage "man/ouroctl-get-business-object-components.1.gz"
  manpage "man/ouroctl-get-business-object-types.1.gz"
  manpage "man/ouroctl-get-business-objects.1.gz"
  manpage "man/ouroctl-get-communicationunit-fields-template.1.gz"
  manpage "man/ouroctl-get-context.1.gz"
  manpage "man/ouroctl-get-data-zones.1.gz"
  manpage "man/ouroctl-get-delete-template.1.gz"
  manpage "man/ouroctl-get-device-configuration-template-template.1.gz"
  manpage "man/ouroctl-get-device-fields-template.1.gz"
  manpage "man/ouroctl-get-device-group-template.1.gz"
  manpage "man/ouroctl-get-field-descriptors.1.gz"
  manpage "man/ouroctl-get-license-code.1.gz"
  manpage "man/ouroctl-get-node-template.1.gz"
  manpage "man/ouroctl-get-register-template.1.gz"
  manpage "man/ouroctl-get-roles.1.gz"
  manpage "man/ouroctl-get-screen-configs.1.gz"
  manpage "man/ouroctl-get-translation.1.gz"
  manpage "man/ouroctl-get-variable-template.1.gz"
  manpage "man/ouroctl-get.1.gz"
  manpage "man/ouroctl-list-communicationunits.1.gz"
  manpage "man/ouroctl-list-deviceconfigurationtemplates.1.gz"
  manpage "man/ouroctl-list-devices.1.gz"
  manpage "man/ouroctl-list-drivers.1.gz"
  manpage "man/ouroctl-list-registers.1.gz"
  manpage "man/ouroctl-list-variables.1.gz"
  manpage "man/ouroctl-list.1.gz"
  manpage "man/ouroctl-report-dataquality.1.gz"
  manpage "man/ouroctl-report-devcommunitchanges.1.gz"
  manpage "man/ouroctl-report-gaps.1.gz"
  manpage "man/ouroctl-report-readout.1.gz"
  manpage "man/ouroctl-report.1.gz"
  manpage "man/ouroctl-set-context.1.gz"
  manpage "man/ouroctl-set.1.gz"
  manpage "man/ouroctl-version.1.gz"
  manpage "man/ouroctl.1.gz"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ouroctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The ouroctl tool is used to control the OuroPlatform deployments.
  EOS
end
