# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroctl" do
  desc "ouroctl controls the ouro platform deployments."
  homepage "https://www.cybroslabs.com/en/products/openhes"
  version "0.9.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroctl"

  on_macos do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/v0.9.16/ouroctl_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "d827a8d9d349496624be5cd0b17b0b0768bedeafd688bf2755cd04877b0f5023"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/v0.9.16/ouroctl_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "4155ed2fe5caa67f551e20032b73aa18bf27d32c547e0a67dd2696fa5841f52c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/v0.9.16/ouroctl_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "43e293c22558a32207667848c9327687944d3ad6aa799767b7c82f8cb3e84af9"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/v0.9.16/ouroctl_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "6d59aeba465cef822c173a0b43a0928084f2b3bfe8ab7519e3c966f942b0b76b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ouroctl"]
    end
  end

  caveats do
    "The ouroctl tool is used to control the ouro platform deployments."
  end

  # No zap stanza required
end
