# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroctl" do
  name "ouroctl"
  desc "ouroctl controls the OuroPlatform deployments."
  homepage "https://www.cybroslabs.com/en/products/openhes"
  version "ouroctl-v0.25.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroctl"
  manpage "man/ouroctl-apply-field-descriptors.1.gz"
  manpage "man/ouroctl-apply-gulf.1.gz"
  manpage "man/ouroctl-apply-license.1.gz"
  manpage "man/ouroctl-apply-screen-configs.1.gz"
  manpage "man/ouroctl-apply-secrets.1.gz"
  manpage "man/ouroctl-apply-template.1.gz"
  manpage "man/ouroctl-apply-translation.1.gz"
  manpage "man/ouroctl-apply.1.gz"
  manpage "man/ouroctl-delete-template.1.gz"
  manpage "man/ouroctl-delete.1.gz"
  manpage "man/ouroctl-get-communicationunit-fields-template.1.gz"
  manpage "man/ouroctl-get-context.1.gz"
  manpage "man/ouroctl-get-delete-template.1.gz"
  manpage "man/ouroctl-get-device-configuration-template-template.1.gz"
  manpage "man/ouroctl-get-device-fields-template.1.gz"
  manpage "man/ouroctl-get-device-group-template.1.gz"
  manpage "man/ouroctl-get-field-descriptors.1.gz"
  manpage "man/ouroctl-get-license-code.1.gz"
  manpage "man/ouroctl-get-node-template.1.gz"
  manpage "man/ouroctl-get-register-template.1.gz"
  manpage "man/ouroctl-get-screen-configs.1.gz"
  manpage "man/ouroctl-get-translation.1.gz"
  manpage "man/ouroctl-get-variable-template.1.gz"
  manpage "man/ouroctl-get.1.gz"
  manpage "man/ouroctl-list-communicationunits.1.gz"
  manpage "man/ouroctl-list-deviceconfigurationtemplates.1.gz"
  manpage "man/ouroctl-list-devices.1.gz"
  manpage "man/ouroctl-list-drivers.1.gz"
  manpage "man/ouroctl-list-registers.1.gz"
  manpage "man/ouroctl-list-variables.1.gz"
  manpage "man/ouroctl-list.1.gz"
  manpage "man/ouroctl-report-dataquality.1.gz"
  manpage "man/ouroctl-report-devcommunitchanges.1.gz"
  manpage "man/ouroctl-report-gaps.1.gz"
  manpage "man/ouroctl-report-readout.1.gz"
  manpage "man/ouroctl-report.1.gz"
  manpage "man/ouroctl-set-context.1.gz"
  manpage "man/ouroctl-set.1.gz"
  manpage "man/ouroctl-version.1.gz"
  manpage "man/ouroctl.1.gz"

  on_macos do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Darwin_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "6723c641e75491ba8953c1966e93956bf57d36ed5ce302e4b54a76eea5e24d06"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Darwin_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "ff2d4a2f5d73282f48b2e04654a8ecb9dda942868cc90b690033a832fd43b69c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Linux_x86_64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "2eb97861fcfbe126b9c432478d3431063d1bac429100d96bb04b6a1988cb47b6"
    end
    on_arm do
      url "https://github.com/cybroslabs/homebrew-tools/releases/download/#{version}/ouroctl_Linux_arm64.tar.gz",
        verified: "github.com/cybroslabs/homebrew-tools"
      sha256 "d0d8d4615cbdf0257905b7835fe6ef6513d7bd739921cac844f2868477d3af19"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ouroctl"]
    end
  end

  caveats do
    "The ouroctl tool is used to control the OuroPlatform deployments."
  end

  # No zap stanza required
end
